- name: Deploy haproxy load balancer
  hosts:        load_balancers
  gather_facts: false
  become:       true

  roles:

  - role: deploy_haproxy

  - role: configure_firewall
    vars:
      firewall_services:
        - http
      firewall_tcp_ports:
        - 5000

