- name: Deploy, configure, and populate flask repo and virtualenv
  hosts:        app_servers
  become:       true
  gather_facts: false
  tags:
    - application_servers
    - flask

  roles:
  - role: deploy_flask

  - role: configure_firewall
    vars:
      firewall_services:
        - http
      firewall_tcp_ports:
        - 8080
