---
- name: Configure Database
  hosts:        database_servers
  gather_facts: false
  become:       true

  roles:

  - role: deploy_database

  - role: configure_firewall
    vars:
      firewall_services:
        - postgresql

