---
- name: Testing!
  hosts: app_servers,database_servers,load_balancers
  gather_facts: false


  tasks:


    - command: hostname
      register: output

    - debug:
        var: output.stdout_lines

