---
# tasks file for configure_servers
- name: Ensure DNS configuration
  command: >-
    nmcli connection modify "System eth0"
    ipv4.ignore-auto-dns yes
    ipv4.dns {{ ansible_default_ipv4.address }}
    +ipv4.dns {{ ansible_dns.nameservers.0 }}
    +ipv4.dns 8.8.8.8

- name: Restart netowrking
  service:
    name: NetworkManager
    state: restarted

- name: Install katello-ca-consumer package
  yum:
    name:              http://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
    state:             present
    disable_gpg_check: true

- name: register system and attach subs
  redhat_subscription:
    state:         present
    activationkey: "{{ satellite_activationkey }}"
    org_id:        "{{ satellite_org }}"
    auto_attach:   true

