---
- name: Manage instances
  openstack.cloud.server:
    cloud:           "{{ GUID }}-project"
    name:            "{{ instance.name }}"
    state:           "{{ server_state }}"
    image:           "{{ instance.image }}"
    flavor:          "{{ instance.flavor }}"
    key_name:        "{{ instance.keypair }}"
    wait:            yes
    security_groups: "{{ instance.security_group }}"
    delete_fip:      yes
    nics:
      - net-name:    "{{ instance.network }}"
    meta: "AnsibleGroup={{instance.metadata.AnsibleGroup}},deployment_name=dev"
    user_data:
      manage_resolv_conf: true
      resolv_conf:
        nameservers: "192.168.50.79"
  loop: "{{ instances }}"
  loop_control:
    label:    "{{ instance.name }}"
    loop_var: instance
  register: created_instances

- name: Get Openstack server info
  os_server_info:
    cloud:  "{{ GUID }}-project"
    server: "{{ instance.name }}"
  loop:     "{{ instances }}"
  loop_control:
    label:    "{{ instance.name }}"
    loop_var: instance
  register: created_instances

- name: Wait for host to respond
  wait_for: 
    host:  "{{ created_instance.1.private_v4 }}"
    port:  22
    state: started
  loop: "{{ created_instances.results|subelements('openstack_servers') }}"
  loop_control:
    loop_var: created_instance
    label:    "{{ created_instance.1.name }}"

    
